### ISSUE TITLE
No puede abrir la base de datos desde el login

### ISSUE THREAD

**Issue by jvicentem** [jmcolmenar/erp-isi-2015-2016#9]
Creo este "issue" para hablar de este problema que creo que también le pasa al grupo del módulo 2.

Error en el caso del módulo 4: [Fri Dec 4 10:48:54 2015] ::1:34577 [200]: /src/common/login.php - Uncaught exception 'Exception' with message 'Unable to open database: unable to open database file' in src/database/ProductsSqliteUtils.inc:18

Creo que el problema este es el problema:
http://yagudaev.com/posts/resolving-php-relative-path-problem/

**Comment by jmcolmenar** [comment]
Hay que utilizar  $_SERVER['DOCUMENT_ROOT']. Haced pull del remote principal para obtener la corrección.
